[build-system]
requires = ["flit_core >=3.2,<4"]  # Specify Flit version requirement
build-backend = "flit_core.buildapi"

[project]
name = "slal-to-slsb"
version = "0.1.0" 
description = ""
dependencies = ["marshmallow", "packaging"]